// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNgTTU075ZyklCmd9U-YbSDpQAPpPLDig',
    appId: '1:492309602046:web:c80a18782554a529bd0faf',
    messagingSenderId: '492309602046',
    projectId: 'shop-ab-96d78',
    authDomain: 'shop-ab-96d78.firebaseapp.com',
    storageBucket: 'shop-ab-96d78.firebasestorage.app',
    measurementId: 'G-B85PN3TW07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZx1LDcspeDYiqBJxHir1lFCiAI2rvUwc',
    appId: '1:492309602046:android:13a9fb29398cc6ebbd0faf',
    messagingSenderId: '492309602046',
    projectId: 'shop-ab-96d78',
    storageBucket: 'shop-ab-96d78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaWnF2bpP2vj_Fna0ooJWbk9Jrekyo_60',
    appId: '1:492309602046:ios:5641c3a0ae573769bd0faf',
    messagingSenderId: '492309602046',
    projectId: 'shop-ab-96d78',
    storageBucket: 'shop-ab-96d78.firebasestorage.app',
    iosBundleId: 'com.example.shopeAb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaWnF2bpP2vj_Fna0ooJWbk9Jrekyo_60',
    appId: '1:492309602046:ios:5641c3a0ae573769bd0faf',
    messagingSenderId: '492309602046',
    projectId: 'shop-ab-96d78',
    storageBucket: 'shop-ab-96d78.firebasestorage.app',
    iosBundleId: 'com.example.shopeAb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNgTTU075ZyklCmd9U-YbSDpQAPpPLDig',
    appId: '1:492309602046:web:9fa065e33087f895bd0faf',
    messagingSenderId: '492309602046',
    projectId: 'shop-ab-96d78',
    authDomain: 'shop-ab-96d78.firebaseapp.com',
    storageBucket: 'shop-ab-96d78.firebasestorage.app',
    measurementId: 'G-3R976TETH0',
  );
}
